services:
  database:
    image: "postgres:16.0-alpine3.18"
    env_file:
    - ../.env
    ports:
      - "5432:5432" #-"host:guest"

#quando o compose não está na raiz do projeto, é necessário indicar onde ele está com o comando:
#sudo docker compose -f infra/compose.yaml up
